import Hero from "@/components/Hero";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
//https://cdn.dribbble.com/users/746931/screenshots/16077352/media/2b4e8416fe883fccb9ab5e78be6bdd6f.png?compress=1&resize=1600x1200
export default function Home() {
  return (
    <>
      <Head>
        <title>Ashiks Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-amiri">
        <Hero />
      </main>
    </>
  );
}
